let schemes = {
  latin: {
    ke: {},
  },
};
let FROM;
let TO;
(schemes.latin.ke.jawa = {
  virama: "꧀",
  pengapitAngka: "꧇",
  nglegena: {
    k: "ꦏ",
    kh: "ꦏ꦳",
    q: "ꦐ",
    g: "ꦒ",
    gh: "ꦒ꦳",
    ng: "ꦔ",
    c: "ꦕ",
    j: "ꦗ",
    z: "ꦗ꦳",
    ny: "ꦚ",
    th: "ꦛ",
    dh: "ꦝ",
    t: "ꦠ",
    d: "ꦢ",
    n: "ꦤ",
    p: "ꦥ",
    f: "ꦥ꦳",
    b: "ꦧ",
    m: "ꦩ",
    y: "ꦪ",
    r: "ꦫ",
    l: "ꦭ",
    w: "ꦮ",
    v: "ꦮ꦳",
    s: "ꦱ",
    h: "ꦲ",
  },
  swara: {
    a: "ꦄ",
    i: "ꦆ",
    u: "ꦈ",
    é: "ꦌ",
    e: "ꦄꦼ",
    eu: "ꦲꦼꦴ",
    o: "ꦎ",
    re: "ꦉ",
    reu: "ꦉꦴ",
    le: "ꦊ",
    leu: "ꦋ",
  },
  mandaswara: {
    y: "ꦾ",
    r: "ꦿ",
  },
  panyigeg: {
    ng: "ꦁ",
    h: "ꦃ",
    r: "ꦂ",
  },
  sandhanganSwara: {
    a: "",
    i: "ꦶ",
    u: "ꦸ",
    é: "ꦺ",
    e: "ꦼ",
    eu: "ꦼꦴ",
    o: "ꦺꦴ",
    re: "ꦽ",
    reu: "ꦽꦴ",
    le: "꧀ꦭꦼ",
    leu: "ꦭꦼꦴ",
  },
  pepadan: {
    ".": "꧉",
    ",": "꧈",
  },
  angka: {
    0: "꧐",
    1: "꧑",
    2: "꧒",
    3: "꧓",
    4: "꧔",
    5: "꧕",
    6: "꧖",
    7: "꧗",
    8: "꧘",
    9: "꧙",
  },
  lainnya: {},
}),
  (schemes.latin.ke.sunda = {
    virama: "᮪",
    pengapitAngka: "|",
    nglegena: {
      k: "ᮊ",
      q: "ᮋ",
      g: "ᮌ",
      ng: "ᮍ",
      c: "ᮎ",
      j: "ᮏ",
      z: "ᮐ",
      ny: "ᮑ",
      t: "ᮒ",
      d: "ᮓ",
      n: "ᮔ",
      p: "ᮕ",
      f: "ᮖ",
      b: "ᮘ",
      m: "ᮙ",
      y: "ᮚ",
      r: "ᮛ",
      l: "ᮜ",
      w: "ᮝ",
      v: "ᮗ",
      s: "ᮞ",
      h: "ᮠ",
    },
    swara: {
      a: "ᮃ",
      i: "ᮄ",
      u: "ᮅ",
      é: "ᮆ",
      e: "ᮈ",
      eu: "ᮉ",
      o: "ᮇ",
      reu: "ᮻ",
      leu: "ᮼ",
    },
    mandaswara: {
      y: "ᮡ",
      r: "ᮢ",
      l: "ᮣ",
    },
    panyigeg: {
      ng: "ᮀ",
      h: "ᮂ",
      r: "ᮁ",
    },
    sandhanganSwara: {
      a: "",
      i: "ᮤ",
      u: "ᮥ",
      é: "ᮦ",
      e: "ᮨ",
      eu: "ᮩ",
      o: "ᮧ",
    },
    pepadan: {},
    angka: {
      0: "᮰",
      1: "᮱",
      2: "᮲",
      3: "᮳",
      4: "᮴",
      5: "᮵",
      6: "᮶",
      7: "᮷",
      8: "᮸",
      9: "᮹",
    },
    lainnya: {},
  }),
  (schemes.latin.ke.batak = {
    virama: "᯲",
    pengapitAngka: "",
    nglegena: {
      k: "ᯃ",
      q: "ᯂ",
      g: "ᯎ",
      ng: "ᯝ",
      c: "ᯡ",
      j: "ᯐ",
      z: "ᯐ",
      ny: "ᯠ",
      t: "ᯖ",
      d: "ᯑ",
      n: "ᯉ",
      nd: "ᯢ",
      p: "ᯇ",
      f: "ᯇ",
      b: "ᯅ",
      m: "ᯔ",
      mb: "ᯣ",
      y: "ᯛ",
      r: "ᯒ",
      l: "ᯞ",
      w: "ᯋ",
      v: "ᯇ",
      s: "ᯘ",
      h: "ᯂ",
    },
    swara: {
      a: "ᯀ",
      i: "ᯤ",
      u: "ᯥ",
    },
    mandaswara: {},
    panyigeg: {
      ng: "ᯰ",
      h: "ᯱ",
    },
    sandhanganSwara: {
      a: "",
      i: "ᯪ",
      u: "ᯮ",
      é: "ᯩ",
      e: "ᯧ",
      o: "ᯬ",
    },
    pepadan: {},
    angka: {},
    lainnya: {},
  }),
  (schemes.latin.ke.bali = {
    virama: "᭄",
    pengapitAngka: "",
    nglegena: {
      k: "ᬓ",
      q: "᭄",
      g: "ᬕ",
      ng: "ᬗ",
      c: "ᬘ",
      j: "ᬚ",
      z: "ᬚ᬴",
      ny: "ᬜ",
      t: "ᬢ",
      d: "ᬤ",
      n: "ᬦ",
      p: "ᬧ",
      f: "ᬧ᬴",
      b: "ᬩ",
      m: "ᬫ",
      y: "ᬬ",
      r: "ᬭ",
      l: "ᬮ",
      w: "ᬯ",
      v: "ᬯ᬴",
      s: "ᬲ",
      h: "ᬳ",
    },
    swara: {
      a: "ᬅ",
      i: "ᬇ",
      u: "ᬳᬸ",
      é: "ᬳᬾ",
      e: "ᬳᬾ",
      o: "ᬑ",
    },
    mandaswara: {},
    panyigeg: {
      ng: "ᬂ",
      h: "ᬄ",
      r: "ᬃ",
    },
    sandhanganSwara: {
      a: "",
      ai: "ᬿ",
      au: "ᭁ",
      i: "ᬶ",
      u: "ᬸ",
      é: "ᬾ",
      e: "ᭂ",
      o: "ᭀ",
      re: "ᬺ",
      le: "ᬼ",
    },
    pepadan: {
      ".": "᭟",
      ",": "᭞",
    },
    angka: {
      0: "᭐",
      1: "᭑",
      2: "᭒",
      3: "᭓",
      4: "᭔",
      5: "᭕",
      6: "᭖",
      7: "᭗",
      8: "᭘",
      9: "᭙",
    },
    lainnya: {},
  }),
  (schemes.latin.ke.rejang = {
    virama: "꥓",
    pengapitAngka: "",
    nglegena: {
      k: "ꤰ",
      g: "ꤱ",
      ng: "ꤲ",
      c: "ꤹ",
      j: "ꤺ",
      ny: "ꤻ",
      t: "ꤳ",
      d: "ꤴ",
      n: "ꤵ",
      nd: "ꥄ",
      p: "ꤶ",
      b: "ꤷ",
      m: "ꤸ",
      mb: "ꥂ",
      y: "ꤿ",
      r: "ꤽ",
      l: "ꤾ",
      w: "ꥀ",
      s: "ꤼ",
      h: "ꥁ",
    },
    swara: {
      a: "ꥆ",
      i: "",
      u: "",
      é: "",
      e: "",
      eu: "",
      o: "",
      re: "",
    },
    mandaswara: {},
    panyigeg: {
      n: "ꥐ",
      ng: "ꥏ",
      h: "ꥒ",
      r: "ꥑ",
    },
    sandhanganSwara: {
      a: "",
      ai: "ꥊ",
      au: "ꥌ",
      i: "ꥇ",
      u: "ꥈ",
      é: "ꥎ",
      e: "ꥉ",
      eu: "ꥍ",
      o: "ꥋ",
    },
    pepadan: {},
    angka: {},
    lainnya: {},
  }),
  (sundakelatin = {
    araka: {
      ᮊ: "k",
      ᮗ: "v",
      ᮘ: "b",
      ᮙ: "m",
      ᮚ: "y",
      ᮛ: "r",
      ᮜ: "l",
      ᮝ: "w",
      ᮞ: "s",
      ᮟ: "x",
      ᮖ: "f",
      ᮕ: "p",
      ᮔ: "n",
      ᮋ: "q",
      ᮌ: "g",
      ᮍ: "ng",
      ᮎ: "c",
      ᮏ: "j",
      ᮐ: "z",
      ᮑ: "ny",
      ᮒ: "t",
      ᮓ: "d",
      ᮠ: "h",
      ᮃ: "a",
      ᮄ: "i",
      ᮅ: "u",
      ᮆ: "é",
      ᮇ: "o",
      ᮈ: "e",
      ᮉ: "eu",
      "ᮤ": "i",
      "ᮥ": "u",
      "ᮦ": "é",
      "ᮧ": "o",
      "ᮨ": "e",
      "ᮩ": "eu",
      "᮪": "",
      "ᮡ": "y",
      "ᮢ": "r",
      "ᮣ": "l",
      "ᮬ": "m",
      "ᮭ": "w",
      "᮰": "0",
      "᮸": "8",
      "᮷": "7",
      "᮶": "6",
      "᮵": "5",
      "᮴": "4",
      "᮳": "3",
      "᮲": "2",
      "᮱": "1",
      "᮹": "9",
      "ᮀ": "ng",
      "ᮁ": "r",
      "ᮂ": "h",
    },
    regna: {
      konsonan: "ᮊ|ᮗ|ᮘ|ᮙ|ᮚ|ᮛ|ᮜ|ᮝ|ᮞ|ᮟ|ᮖ|ᮕ|ᮔ|ᮋ|ᮌ|ᮍ|ᮎ|ᮏ|ᮐ|ᮑ|ᮒ|ᮓ|ᮠ",
      swara: "ᮃ|ᮄ|ᮅ|ᮆ|ᮇ|ᮈ|ᮉ",
      rarangken: "ᮤ|ᮥ|ᮦ|ᮧ|ᮨ|ᮩ|᮪",
      subjoin: "ᮡ|ᮢ|ᮣ|ᮬ|ᮭ",
      angka: "᮰|᮸|᮷|᮶|᮵|᮴|᮳|᮲|᮱|᮹",
      ahir: "ᮀ|ᮁ|ᮂ",
    },
  }),
  (jawakelatin = {
    araka: {
      ꦯ: "s",
      ꦣ: "d",
      ꦢ: "d",
      ꦡ: "t",
      ꦠ: "t",
      ꦟ: "d",
      ꦞ: "d",
      ꦝ: "d",
      ꦜ: "th",
      ꦛ: "th",
      ꦤ: "n",
      ꦥ꦳: "f",
      ꦮ꦳: "v",
      ꦏ꦳: "kh",
      ꦒ꦳: "gh",
      ꦗ꦳: "z",
      ꦥ: "p",
      ꦮ: "w",
      ꦭ: "l",
      ꦬ: "r",
      ꦫ: "r",
      ꦰ: "s",
      ꦩ: "m",
      ꦨ: "b",
      ꦧ: "b",
      ꦦ: "p",
      ꦚ: "ny",
      ꦙ: "j",
      ꦪ: "y",
      ꦋ: "ng",
      ꦊ: "ng",
      ꦉ: "re",
      ꦲ: "h",
      ꦏ: "k",
      ꦘ: "ny",
      ꦗ: "j",
      ꦱ: "s",
      ꦕ: "c",
      ꦔ: "ng",
      ꦓ: "g",
      ꦒ: "g",
      ꦑ: "k",
      ꦐ: "k",
      ꦖ: "c",
      ꦍ: "ai",
      ꦈ: "u",
      ꦅ: "i",
      ꦇ: "Ī",
      ꦆ: "i",
      ꦄ: "a",
      ꦎ: "o",
      ꦌ: "é",
      "ꦺꦴ": "o",
      "ꦷ": "i",
      "꧀": "",
      "ꦼ": "e",
      "ꦶ": "i",
      "ꦹ": "u",
      "ꦸ": "u",
      "ꦺ": "é",
      "ꦿ": "r",
      "ꦾ": "y",
      "꧙": "9",
      "꧘": "8",
      "꧗": "7",
      "꧖": "6",
      "꧕": "5",
      "꧔": "4",
      "꧓": "3",
      "꧐": "0",
      "꧑": "1",
      "꧒": "2",
      "꧈": ",",
      "ꦂ": "r",
      "ꦃ": "h",
      "ꦁ": "ng",
      "꧉": ".",
    },
    regna: {
      konsonan:
        "ꦯ|ꦣ|ꦢ|ꦡ|ꦠ|ꦟ|ꦞ|ꦝ|ꦜ|ꦛ|ꦤ|ꦥ꦳|ꦮ꦳|ꦏ꦳|ꦒ꦳|ꦗ꦳|ꦥ|ꦮ|ꦭ|ꦬ|ꦫ|ꦰ|ꦩ|ꦨ|ꦧ|ꦦ|ꦚ|ꦙ|ꦪ|ꦋ|ꦊ|ꦉ|ꦲ|ꦏ|ꦘ|ꦗ|ꦱ|ꦕ|ꦔ|ꦓ|ꦒ|ꦑ|ꦐ|ꦖ",
      swara: "ꦍ|ꦈ|ꦅ|ꦇ|ꦆ|ꦄ|ꦎ|ꦌ",
      rarangken: "ꦺꦴ|ꦷ|꧀|ꦼ|ꦶ|ꦹ|ꦸ|ꦺ",
      subjoin: "ꦿ|ꦾ",
      angka: "꧙|꧘|꧗|꧖|꧕|꧔|꧓|꧐|꧑|꧒",
      ahir: "꧈|ꦂ|ꦃ|ꦁ|꧉",
    },
  }),
  (balikelatin = {
    araka: {
      ᬯ᬴: "v",
      ᬚ᬴: "z",
      ᬧ᬴: "f",
      ᬨ: "p",
      ᬧ: "p",
      ᬦ: "n",
      ᬥ: "d",
      ᬤ: "d",
      ᬣ: "t",
      ᬢ: "t",
      ᬡ: "n",
      ᬠ: "d",
      ᬟ: "d",
      ᬞ: "d",
      ᬩ: "b",
      ᬪ: "b",
      ᬳ: "h",
      ᬲ: "s",
      ᬱ: "s",
      ᬰ: "s",
      ᬯ: "w",
      ᬮ: "l",
      ᬭ: "r",
      ᬬ: "y",
      ᬫ: "m",
      ᬝ: "t",
      ᬜ: "ny",
      ᬛ: "j",
      ᬍ: "l",
      ᬌ: "r",
      ᬖ: "g",
      ᬋ: "r",
      ᬓ: "k",
      ᬔ: "k",
      ᬕ: "g",
      ᬗ: "ng",
      ᬘ: "c",
      ᬙ: "c",
      ᬚ: "j",
      ᬎ: "l",
      ᬳᬾ: "é",
      ᬳᬸ: "u",
      ᬆ: "a",
      ᬅ: "a",
      ᬇ: "i",
      ᬈ: "i",
      ᬉ: "u",
      ᬊ: "u",
      ᬏ: "e",
      ᬑ: "o",
      ᬒ: "o",
      ᬐ: "ai",
      "ᭀ": "o",
      "ᭁ": "au",
      "ᬻ": "re",
      "ᭃ": "e",
      "᭄": "",
      "ᬿ": "é",
      "ᬾ": "é",
      "ᬶ": "i",
      "ᬷ": "i",
      "ᬸ": "u",
      "ᬹ": "u",
      "ᬺ": "re",
      "ᬼ": "le",
      "ᬽ": "le",
      "ᭂ": "e",
      "᭗": "7",
      "᭙": "9",
      "᭘": "8",
      "᭖": "6",
      "᭕": "5",
      "᭔": "4",
      "᭓": "3",
      "᭒": "2",
      "᭐": "0",
      "᭑": "1",
      "ᬂ": "ng",
      "ᬃ": "r",
      "ᬄ": "h",
      "᭟": ",",
      "᭞": ",",
    },
    regna: {
      konsonan:
        "ᬯ᬴|ᬚ᬴|ᬧ᬴|ᬨ|ᬧ|ᬦ|ᬥ|ᬤ|ᬣ|ᬢ|ᬡ|ᬠ|ᬟ|ᬞ|ᬩ|ᬪ|ᬳ|ᬲ|ᬱ|ᬰ|ᬯ|ᬮ|ᬭ|ᬬ|ᬫ|ᬝ|ᬜ|ᬛ|ᬍ|ᬌ|ᬖ|ᬋ|ᬓ|ᬔ|ᬕ|ᬗ|ᬘ|ᬙ|ᬚ|ᬎ",
      swara: "ᬳᬾ|ᬳᬸ|ᬳᬾ|ᬆ|ᬅ|ᬇ|ᬈ|ᬉ|ᬊ|ᬏ|ᬑ|ᬒ|ᬐ",
      rarangken: "ᭀ|ᭁ|ᬻ|ᭃ|᭄|ᬿ|ᬾ|ᬶ|ᬷ|ᬸ|ᬹ|ᬺ|ᬼ|ᬽ|ᭂ",
      subjoin: "",
      angka: "᭗|᭙|᭘|᭖|᭕|᭔|᭓|᭒|᭐|᭑",
      ahir: "ᬂ|ᬃ|ᬄ|᭟|᭞",
    },
  }),
  (batakkelatin = {
    araka: {
      ᯂ: "h",
      ᯔ: "m",
      ᯕ: "m",
      ᯖ: "t",
      ᯗ: "t",
      ᯘ: "s",
      ᯙ: "s",
      ᯚ: "s",
      ᯛ: "y",
      ᯜ: "y",
      ᯝ: "ng",
      ᯞ: "l",
      ᯟ: "l",
      ᯠ: "ny",
      ᯡ: "c",
      ᯢ: "nd",
      ᯓ: "r",
      ᯒ: "r",
      ᯃ: "h",
      ᯄ: "h",
      ᯅ: "b",
      ᯆ: "b",
      ᯇ: "p",
      ᯈ: "p",
      ᯉ: "n",
      ᯊ: "n",
      ᯋ: "w",
      ᯌ: "w",
      ᯍ: "w",
      ᯎ: "g",
      ᯏ: "g",
      ᯐ: "j",
      ᯑ: "d",
      ᯣ: "mb",
      ᯀ: "a",
      ᯁ: "a",
      ᯤ: "i",
      ᯥ: "u",
      "ᯧ": "e",
      "ᯨ": "e",
      "ᯩ": "ee",
      "ᯪ": "i",
      "ᯫ": "i",
      "ᯬ": "o",
      "ᯭ": "o",
      "ᯮ": "u",
      "᯲": "",
      "ᯰ": "ng",
      "ᯱ": "h",
    },
    regna: {
      konsonan:
        "ᯂ|ᯔ|ᯕ|ᯖ|ᯗ|ᯘ|ᯙ|ᯚ|ᯛ|ᯜ|ᯝ|ᯞ|ᯟ|ᯠ|ᯡ|ᯢ|ᯓ|ᯒ|ᯃ|ᯄ|ᯅ|ᯆ|ᯇ|ᯈ|ᯉ|ᯊ|ᯋ|ᯌ|ᯍ|ᯎ|ᯏ|ᯐ|ᯑ|ᯣ",
      swara: "ᯀ|ᯁ|ᯤ|ᯥ",
      rarangken: "ᯧ|ᯨ|ᯩ|ᯪ|ᯫ|ᯬ|ᯭ|ᯮ|᯲",
      subjoin: "",
      angka: "",
      ahir: "ᯰ|ᯱ",
    },
  }),
  (rejangkelatin = {
    araka: {
      ꤰ: "k",
      ꤼ: "s",
      ꤽ: "r",
      ꤾ: "l",
      ꤿ: "y",
      ꥀ: "w",
      ꥁ: "h",
      ꥂ: "mb",
      ꥃ: "ngg",
      ꥄ: "nd",
      ꤻ: "ny",
      ꤺ: "j",
      ꤱ: "g",
      ꤲ: "ng",
      ꤳ: "t",
      ꤴ: "d",
      ꤵ: "n",
      ꤶ: "p",
      ꤷ: "b",
      ꤸ: "m",
      ꤹ: "c",
      ꥅ: "nyj",
      ꥆ: "a",
      "ꥇ": "i",
      "ꥐ": "n",
      "ꥎ": "é",
      "ꥍ": "eu",
      "ꥌ": "au",
      "ꥋ": "o",
      "ꥊ": "ai",
      "ꥉ": "e",
      "ꥈ": "u",
      "꥓": "",
      "ꥏ": "ng",
      "ꥑ": "r",
      "ꥒ": "h",
    },
    regna: {
      konsonan: "ꤰ|ꤼ|ꤽ|ꤾ|ꤿ|ꥀ|ꥁ|ꥂ|ꥃ|ꥄ|ꤻ|ꤺ|ꤱ|ꤲ|ꤳ|ꤴ|ꤵ|ꤶ|ꤷ|ꤸ|ꤹ|ꥅ",
      swara: "ꥆ",
      rarangken: "ꥇ|ꥐ|ꥎ|ꥍ|ꥌ|ꥋ|ꥊ|ꥉ|ꥈ|꥓",
      subjoin: "",
      angka: "",
      ahir: "ꥏ|ꥑ|ꥒ",
    },
  });
var $ = jQuery.noConflict();

function konversi() {
  var a = jQuery("#idInput").attr("tika");
  jQuery("#idInput").attr("to"), jQuery("#idInput").attr("fr");
  let t = jQuery("#txtInput").val();
  if (2 < t.length) jQuery("#copyBtn").fadeIn("slow");
  var r = 0;
  var e = {
    spasi: r,
  };

  switch (a) {
    case "lt_sd":
      var s = transliterateRoman("sunda", t, schemes.latin.ke.sunda);
      jQuery("#txtOutput").val(s);
      break;
    case "sd_lt":
      var s = transliterateAknus("sunda", t, sundakelatin);
      jQuery("#txtOutput").val(s);
      break;
    case "lt_jw":
      var s = transliterateRoman("jawa", t, schemes.latin.ke.jawa, e);
      jQuery("#txtOutput").val(s);
      break;
    case "jw_lt":
      var s = transliterateAknus("jawa", t, jawakelatin);
      jQuery("#txtOutput").val(s);
      break;
    default:
      jQuery("#txtOutput").html(" ... ");
  }
}

function salin() {
  var a = $("#txtOutput").text();

  var range = document.createRange();
  range.selectNode(document.getElementById("txtOutput"));
  window.getSelection().removeAllRanges(); // clear current selection
  window.getSelection().addRange(range); // to select text
  document.execCommand("copy");
  window.getSelection().removeAllRanges();

  $("#salin_info").fadeIn(1e3, function () {
    setTimeout(function () {
      $("#salin_info").fadeOut(1e3);
    }, 3e3);
  });
}

$(document).ready(function () {
  $("#reverse").click(function () {
    var txtInput = $("#txtInput").val();
    var txtOutput = $("#txtOutput").val();
    $("#txtInput").val(txtOutput);
    $("#txtOutput").val(txtInput);
    $("#txtInput").toggleClass("aksara_sunda");
    $("#txtOutput").toggleClass("aksara_sunda");

    if ($("#idInput").text() == "Latin") {
      $("#idInput").text("Aksara Sunda");
      $("#idInput").attr("lang", "sd");
      $("#idInput").attr("tika", "sd_lt");
      $("#idInput").attr("fr", "sd");
      $("#idInput").attr("to", "lt");
      $("#idOutput").text("Latin");
      $(this).toggleClass("aksara_sunda");
    } else {
      $("#idInput").text("Latin");
      $("#idInput").attr("lang", "lt");
      $("#idInput").attr("tika", "lt_sd");
      $("#idInput").attr("fr", "lt");
      $("#idInput").attr("to", "sd");
      $("#idOutput").text("Aksara Sunda");
    }
  });

  $("#txtInput").on("keyup", function () {
    if ($(this).val().length > 2) {
      konversi();
    } else {
      $("#txtOutput").val("");
      $("#copyBtn").css("display", "none");
    }
  });

  $("#copyBtn").on("click", function () {
    salin();
  });

  $("#download-font-sunda").on("click", function () {
    e.preventDefault(); //stop the browser from following
    window.location.href =
      "https://cdn.jsdelivr.net/gh/agusls/generator@main/sunda/fonts/sunda_prada-webfont.ttf";
  });
});
